# Generated by Django 3.0 on 2020-12-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='tag',
            field=models.CharField(choices=[('People', 'People'), ('Pets', 'Pets'), ('Nature', 'Nature'), ('Action', 'Action'), ('Lifestyle', 'Lifestyle')], default='people', max_length=9),
        ),
    ]
