# Generated by Django 3.0 on 2020-12-22 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201222_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='owner',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='pic',
        ),
        migrations.AddField(
            model_name='like',
            name='pic_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.Pic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pic',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='likes', through='api.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
